version: "3"
services:
  nginx:
    image: pomerium/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  autocache:
    environment:
      - VIRTUAL_PROTO=http
      - VIRTUAL_HOST=autocache.localhost
      - VIRTUAL_PORT=80
      - NODES=autocache
    image: autocache
    expose:
      - 80
